# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payments

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments

spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments
      app: payments
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "payments"
      creationTimestamp: null
      labels:
        service: payments
        app: payments
    spec:
      containers:
      - image: hashicorpdemoapp/payments:v0.0.11
        imagePullPolicy: Always
        name: payments
        ports:
        - containerPort: 8080
      serviceAccount: payments
